version: "3"
services:

  documentation:
    image: registry.codenetix.com/documentation/documentation:master
    environment:
      - THEME=slate
    volumes:
      - .:/schema

  generator:
    image: registry.codenetix.com/documentation/generator:master
    volumes:
      - .:/schema
      - ./examples:/out
      - ./.generatorignore:/generator/.generatorignore

  mock:
    image: registry.codenetix.com/documentation/mock:master
    volumes:
      - .:/schema

  proxy:
    image: codenetix/nginx-reverse-proxy
    ports:
      - 80:80
    links:
      - documentation:documentation
      - mock:mock
    environment:
      - SET_HTTP_proxy_buffering='off'
      - SET_HTTP_proxy_cache='off'
      - SET_HTTP_proxy_connect_timeout='300'
      - SET_HTTP_proxy_http_version='1.1'
      - SET_HTTP_proxy_read_timeout='300'
      - SET_HTTP_proxy_send_timeout='300'
      - SET_HTTP_send_timeout='300'
      - VH_docs.localhost=http://documentation
      - VH_mock.localhost=http://mock

  testing_mock:
    image: registry.codenetix.com/documentation/testing:master
    links:
      - mock:mock
    environment:
      - TESTING_URI=http://mock/v1
    volumes:
      - .:/schema
